
[[agents]]
id = "test_agent1"
name = "HoloTester1"
public_address = "sandwich--------------------------------------------------------------------------AAAEqzh28L"
key_file = "holo_tester.key"

[[agents]]
id = "test_agent2"
name = "HoloTester2"
public_address = "bagel-----------------------------------------------------------------------------AAADAq0mCu"
key_file = "holo_tester.key"

[[dnas]]
id = "chat_dna"
file = "./dna/hylo-chat.hcpkg"
hash = "Qm328wyq38924y"


[[instances]]
id = "hylo-chat"
dna = "chat_dna"
agent = "test_agent1"
[instances.logger]
type = "simple"
file = "app_spec.log"
[instances.storage]
type = "file"
path = "tmp-storage"


[[interfaces]]
id = "websocket_interface"
[interfaces.driver]
type = "http"
port = 3400
[[interfaces.instances]]
id = "hylo-chat"

#===================================================================

[[ui_bundles]]
id = "main"
root_dir = "./build"
hash = "Qm000"

[[ui_interfaces]]
id = "ui-interface"
bundle = "main"
port = 4000
dna_interface = "websocket_interface"
