export const CREATE_COMMENT = 'CREATE_COMMENT'

export const FETCH_COMMENTS = 'FETCH_COMMENTS'
export const FETCH_FEED_ITEMS = 'FETCH_FEED_ITEMS'
export const FETCH_POST = 'FETCH_POST'
export const FETCH_POSTS = 'FETCH_POSTS'

export const ADD_COMMENT = 'ADD_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const UPDATE_COMMENT = 'UPDATE_COMMENT'

export const ADD_COMMUNITY = 'ADD_COMMUNITY'
export const DELETE_COMMUNITY = 'DELETE_COMMUNITY'
export const UPDATE_COMMUNITY = 'UPDATE_COMMUNITY'

export const ADD_MEMBERSHIP = 'ADD_MEMBERSHIP'
export const DELETE_MEMBERSHIP = 'DELETE_MEMBERSHIP'
export const UPDATE_MEMBERSHIP = 'UPDATE_MEMBERSHIP'

export const ADD_PERSON = 'ADD_PERSON'
export const DELETE_PERSON = 'DELETE_PERSON'
export const UPDATE_PERSON = 'UPDATE_PERSON'

export const ADD_POST = 'ADD_POST'
export const DELETE_POST = 'DELETE_POST'
export const UPDATE_POST = 'UPDATE_POST'

export const ADD_FEED_ITEM = 'ADD_FEED_ITEM'
export const DELETE_FEED_ITEM = 'DELETE_FEED_ITEM'
export const UPDATE_FEED_ITEM = 'UPDATE_FEED_ITEM'

export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER'
export const TOGGLE_COMMUNITIES_DRAWER = 'TOGGLE_COMMUNITIES_DRAWER'

export const EXTRACT_MODEL = 'EXTRACT_MODEL'
