export const _PENDING = '_PENDING'

export const CREATE_COMMENT = 'CREATE_COMMENT'
export const CREATE_COMMENT_PENDING = CREATE_COMMENT + _PENDING

export const FETCH_COMMENTS = 'FETCH_COMMENTS'
export const FETCH_FEED_ITEMS = 'FETCH_FEED_ITEMS'
export const FETCH_POST = 'FETCH_POST'
export const FETCH_POSTS = 'FETCH_POSTS'

export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER'
export const TOGGLE_COMMUNITIES_DRAWER = 'TOGGLE_COMMUNITIES_DRAWER'

export const EXTRACT_MODEL = 'EXTRACT_MODEL'
