export const FETCH_POST = 'FETCH_POST'
export const FETCH_FEEDITEM = 'FETCH_FEEDITEM'

export const ADD_COMMENT = 'ADD_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const UPDATE_COMMENT = 'UPDATE_COMMENT'

export const ADD_COMMUNITY = 'ADD_COMMUNITY'
export const DELETE_COMMUNITY = 'DELETE_COMMUNITY'
export const UPDATE_COMMUNITY = 'UPDATE_COMMUNITY'

export const ADD_PERSON = 'ADD_PERSON'
export const DELETE_PERSON = 'DELETE_PERSON'
export const UPDATE_PERSON = 'UPDATE_PERSON'

export const ADD_POST = 'ADD_POST'
export const DELETE_POST = 'DELETE_POST'
export const UPDATE_POST = 'UPDATE_POST'

export const ADD_FEEDITEM = 'ADD_FEEDITEM'
export const DELETE_FEEDITEM = 'DELETE_FEEDITEM'
export const UPDATE_FEEDITEM = 'UPDATE_FEEDITEM'

export const CHECK_LOGIN = 'CHECK_LOGIN'
export const LOGIN = 'LOGIN'

export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER'
